/*************************************** FOR TEACHER'S MODULE *******************************************/
export const SIGN_UP_TEACHER = "SIGN_UP_TEACHER";
export const SIGN_UP_TEACHER_SUCCESS = "SIGN_UP_TEACHER_SUCCESS";

export const LOGIN_TEACHER = "LOGIN_TEACHER";
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_FB = "LOGIN_TEACHER_FB";
export const LOGIN_TEACHER_FB_SUCCESS = "LOGIN_TEACHER_FB_SUCCESS";
export const LOGIN_TEACHER_GOOGLE = "LOGIN_TEACHER_GOOGLE";
export const LOGIN_TEACHER_GOOGLE_SUCCESS = "LOGIN_TEACHER_GOOGLE_SUCCESS";
export const LOGOUT_TEACHER = "LOGOUT_TEACHER";
export const LOGOUT_TEACHER_SUCCESS = "LOGOUT_TEACHER_SUCCESS";

export const GET_TEACHER_INFO_FROM_FS = "GET_TEACHER_INFO_FROM_FS";
export const GET_TEACHER_INFO_FROM_FS_SUCCESS = "GET_TEACHER_INFO_FROM_FS_SUCCESS";

export const ADD_QUIZ_IN_TEACHERS_RECORD = "ADD_QUIZ_IN_TEACHERS_RECORD";
export const ADD_QUIZ_IN_TEACHERS_RECORD_SUCCESS = "ADD_QUIZ_IN_TEACHERS_RECORD_SUCCESS";

export const UPLOAD_QUIZ = "UPLOAD_QUIZ";
export const UPLOAD_QUIZ_SUCCESS = "UPLOAD_QUIZ_SUCCESS";

export const VIEW_STUDENTS_MARKS = "VIEW_STUDENTS_MARKS";
export const VIEW_STUDENTS_MARKS_SUCCESS = "VIEW_STUDENTS_MARKS_SUCCESS";

export const GET_PREVIOUS_QUIZES_INFO = "GET_PREVIOUS_QUIZES_INFO";
export const GET_PREVIOUS_QUIZES_INFO_SUCCESS = "GET_PREVIOUS_QUIZES_INFO_SUCCESS";
/********************************************************************************************************/


/*************************************** FOR STUDENT'S MODULE *******************************************/
export const SIGN_UP_STUDENT = "SIGN_UP_STUDENT";
export const SIGN_UP_STUDENT_SUCCESS = "SIGN_UP_STUDENT_SUCCESS";

export const LOGIN_STUDENT = "LOGIN_STUDENT";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_FB = "LOGIN_STUDENT_FB";
export const LOGIN_STUDENT_FB_SUCCESS = "LOGIN_STUDENT_FB_SUCCESS";
export const LOGIN_STUDENT_GOOGLE = "LOGIN_STUDENT_GOOGLE";
export const LOGIN_STUDENT_GOOGLE_SUCCESS = "LOGIN_STUDENT_GOOGLE_SUCCESS";
export const LOGOUT_STUDENT = "LOGOUT_STUDENT";
export const LOGOUT_STUDENT_SUCCESS = "LOGOUT_STUDENT_SUCCESS";

export const GET_STUDENT_INFO_FROM_FS = "GET_STUDENT_INFO_FROM_FS";
export const GET_STUDENT_INFO_FROM_FS_SUCCESS = "GET_STUDENT_INFO_FROM_FS_SUCCESS";

export const GET_QUIZ_INFO = "GET_QUIZ_INFO";
export const GET_QUIZ_INFO_SUCCESS = "GET_QUIZ_INFO_SUCCESS";

export const ADD_QUIZ_INFO_IN_STUDENTS_RECORD = "ADD_QUIZ_INFO_IN_STUDENTS_RECORD";
export const ADD_QUIZ_INFO_IN_STUDENTS_RECORD_SUCCESS = "ADD_QUIZ_INFO_IN_STUDENTS_RECORD_SUCCESS";

export const SUBMIT_QUIZ_TO_TEACHER = "SUBMIT_QUIZ_TO_TEACHER"
export const SUBMIT_QUIZ_TO_TEACHER_SUCCESS = "SUBMIT_QUIZ_TO_TEACHER_SUCCESS"
/********************************************************************************************************/

export const QUIZ_DATA_FROM_REAL_TIME_DB = "QUIZ_DATA_FROM_REAL_TIME_DB";
export const QUIZ_DATA_FROM_REAL_TIME_DB_SUCCESS = "QUIZ_DATA_FROM_REAL_TIME_DB_SUCCESS";